version: '2.2'
services:
 
  appscope01:
    image: "cribl/scope:${APPSCOPE_VERSION:-dev-x86_64}"
    container_name: appscope01
    environment:
      SCOPE_EVENT_METRIC: "true"
      SCOPE_EVENT_HTTP: "true"
      SCOPE_EVENT_NET: "true"
      SCOPE_EVENT_FS: "true"
      SCOPE_CRIBL: "${APPSCOPE_DEST:-tcp://cribl01:10090}"
      SCOPE_TAG_container_name: "appscope01"
      LD_PRELOAD: /usr/local/lib/libscope.so
    networks:
      - test_scope_net

  appscope02:
    image: "cribl/scope:${APPSCOPE_VERSION:-dev-x86_64}"
    container_name: appscope02
    environment:
      SCOPE_EVENT_METRIC: "true"
      SCOPE_EVENT_HTTP: "true"
      SCOPE_EVENT_NET: "true"
      SCOPE_EVENT_FS: "true"
      SCOPE_CRIBL: "${APPSCOPE_DEST:-tcp://cribl01:10090}"
      SCOPE_TAG_container_name: "appscope02"
    tty: true
    networks:
      - test_scope_net

  appscope01_tls:
    image: "cribl/scope:${APPSCOPE_VERSION:-dev-x86_64}"
    container_name: appscope01_tls
    environment:
      SCOPE_EVENT_METRIC: "true"
      SCOPE_EVENT_HTTP: "true"
      SCOPE_EVENT_NET: "true"
      SCOPE_EVENT_FS: "true"
      SCOPE_CRIBL: "${APPSCOPE_DEST_TLS:-tcp://cribl01:10091}"
      SCOPE_CRIBL_TLS_ENABLE: "true"
      SCOPE_CRIBL_TLS_CA_CERT_PATH: "${TLS_CA_CERT:-/opt/domain.crt}"
      SCOPE_TAG_container_name: "appscope01_tls"
    tty: true
    networks:
      - test_scope_net

  appscope03_ssh_test:
    build:
      context: ./images
      dockerfile: Dockerfile
    container_name: appscope03_ssh_test
    environment:
      #SCOPE_LOG_LEVEL: "debug"
      #SCOPE_LOG_LEVEL: "trace"
      SCOPE_CRIBL_ENABLE: "false"
      # SCOPE_EVENT_ENABLE: "false"
      SCOPE_METRIC_ENABLE: "false"
      #SCOPE_EVENT_METRIC: "false"
      #SCOPE_EVENT_HTTP: "true"
      #SCOPE_EVENT_NET: "true"
      #SCOPE_EVENT_FS: "true"
      SCOPE_EVENT_DEST: "${APPSCOPE_DEST:-tcp://cribl01:10090}"
      # SCOPE_CRIBL: "${APPSCOPE_DEST:-tcp://cribl01:10090}"
      # SCOPE_EVENT_DEST: "file:///opt/test-runner/events.log"
      # SCOPE_METRIC_DEST: "file:///opt/test-runner/metrics.log"
      #SCOPE_TAG_container_name: "appscope03"
    ports:
      - "2022:22"
    volumes:
      - /home/michalbiesek/Github/appscope:/appscope
    tty: true
    # entrypoint:
    #   - ldscope
    #   - --
    #   - /usr/sbin/sshd
    #   - -D
    networks:
      - test_scope_net
    cap_add:
      - SYS_PTRACE

  cribl01:
    image: "cribl/cribl:${CRIBL_VERSION:-3.4.2}"
    container_name: cribl01
    ports:
      - "${CRIBL_HOST_PORT:-9000}:9000"
    networks:
      - test_scope_net

networks:
  test_scope_net:
    driver: bridge
